language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g bower grunt-cli
install:
  - bower install
  - npm install
before_script:
  - grunt build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
