language: node_js
node_js:
  - 0.10
before_install:
  - openssl aes-256-cbc -K $encrypted_f5a6d6d93a89_key -iv $encrypted_f5a6d6d93a89_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
  - npm install -g npm@2
  - npm --version
  - npm install -g bower grunt-cli
install:
  - bower install
  - npm install
before_script:
  - grunt build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - chmod 600 .travis/deploy_key
  - eval `ssh-agent -s`
  - ssh-add .travis/deploy_key
  - cd dist
  - git remote add deploy git@github.com:fifthweek/fifthweek-web-dist.git
  - git push deploy
